/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:105bfa04-3397-48c9-a81b-a6dcbba8fcc4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_gynjLmQMw",
    "aws_user_pools_web_client_id": "2857989gme36gm5k2sfkusj6ic",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "resume-repository-app-storage-82d5b658230403-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
